server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  datasource:
    url: jdbc:postgresql://project-test.cwknrohnqyor.eu-west-2.rds.amazonaws.com:5432/testdb
    username: awsome_architechs
    password: cloud123
  jpa:
    hibernate:                                                  
      ddl-auto: validate    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect                                      
        format_sql: true
    show-sql: false
