server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  datasource:
    url: jdbc:postgresql://terraform-20240108083020466000000002.cfsrwfbzwtok.eu-west-2.rds.amazonaws.com:5432/aws_customers
    username: postgres
    password: cloud123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:                                                                  
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
